# Generated by Django 4.0.1 on 2022-01-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_user_delete_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_list_users', 'For Admin'), ('can_add_list_students', 'For Teachers'), ('can_see_his_info', 'For students'))},
        ),
    ]
